package report

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/terrypsv/Argus/internal/model"
)

// Markdown writes a report file that renders nicely on GitHub.
func Markdown(w io.Writer, rep model.Report) {
	fmt.Fprintf(w, "# Argus - Security Posture Report\n\n")
	fmt.Fprintf(w, "> Generated by Argus %s on %s\n>\n> Editeur : %s - %s\n\n",
		rep.Version, rep.FinishedAt.Format("2006-01-02 15:04:05 MST"),
		rep.Author, rep.Repository)

	fmt.Fprintf(w, "## Verdict\n\n**%s**\n\n", rep.Verdict)
	if rep.Profile != "" && rep.Profile != "workstation" {
		fmt.Fprintf(w, "Scanned under the `%s` profile: some controls are waived by design for this class of machine.\n\n", rep.Profile)
	}

	fmt.Fprintf(w, "| Axis | Score | Grade | Open issues | Accepted | Without exceptions |\n| --- | --- | --- | --- | --- | --- |\n")
	fmt.Fprintf(w, "| Hardening - is this host configured to resist attack? | %d / 100 | %s | %d | %d | %d (%s) |\n",
		rep.Hardening.Score, rep.Hardening.Grade, rep.Hardening.Issues,
		rep.Hardening.Accepted, rep.Hardening.RawScore, rep.Hardening.RawGrade)
	fmt.Fprintf(w, "| Integrity - is there evidence of tampering? | %d / 100 | %s | %d | %d | %d (%s) |\n\n",
		rep.Integrity.Score, rep.Integrity.Grade, rep.Integrity.Issues,
		rep.Integrity.Accepted, rep.Integrity.RawScore, rep.Integrity.RawGrade)

	fmt.Fprintf(w, "| Severity | Count |\n| --- | --- |\n")
	fmt.Fprintf(w, "| Critical | %d |\n", rep.Counts["CRITICAL"])
	fmt.Fprintf(w, "| High | %d |\n", rep.Counts["HIGH"])
	fmt.Fprintf(w, "| Medium | %d |\n", rep.Counts["MEDIUM"])
	fmt.Fprintf(w, "| Low | %d |\n", rep.Counts["LOW"])
	fmt.Fprintf(w, "| Passed controls | %d |\n", rep.Counts["passed"])
	if rep.Suppressed > 0 {
		fmt.Fprintf(w, "| Accepted exceptions | %d |\n", rep.Suppressed)
	}
	fmt.Fprintf(w, "\n")

	fmt.Fprintf(w, "## Host\n\n")
	fmt.Fprintf(w, "- **Hostname:** %s\n", rep.Host.Hostname)
	fmt.Fprintf(w, "- **OS / Arch:** %s / %s\n", rep.Host.OS, rep.Host.Arch)
	fmt.Fprintf(w, "- **Platform:** %s\n", rep.Host.Platform)
	fmt.Fprintf(w, "- **Kernel:** %s\n", rep.Host.Kernel)
	fmt.Fprintf(w, "- **CPUs:** %d\n\n", rep.Host.NumCPU)

	// Issues grouped by category.
	fmt.Fprintf(w, "## Open findings\n\n")
	byCat := map[string][]model.Finding{}
	var cats []string
	hasIssue := false
	for _, f := range rep.Findings {
		if f.Passed || f.Accepted != "" || (f.Severity == model.SevInfo && f.Err == "") {
			continue
		}
		hasIssue = true
		if _, ok := byCat[f.Category]; !ok {
			cats = append(cats, f.Category)
		}
		byCat[f.Category] = append(byCat[f.Category], f)
	}
	sort.Strings(cats)

	if !hasIssue {
		fmt.Fprintf(w, "_No open issues._\n\n")
	}
	for _, c := range cats {
		fmt.Fprintf(w, "### %s\n\n", strings.Title(c))
		for _, f := range byCat[c] {
			fmt.Fprintf(w, "#### `[%s]` %s\n\n", f.Severity.String(), f.Title)
			fmt.Fprintf(w, "- **ID:** `%s`\n", f.ID)
			if f.Detail != "" {
				fmt.Fprintf(w, "- **Detail:** %s\n", f.Detail)
			}
			if f.Remediation != "" {
				fmt.Fprintf(w, "- **Remediation:** %s\n", f.Remediation)
			}
			if f.Superseded != "" {
				fmt.Fprintf(w, "- **Counted once, through:** `%s`\n", f.Superseded)
			}
			if len(f.References) > 0 {
				var refs []string
				for _, r := range f.References {
					refs = append(refs, fmt.Sprintf("%s `%s` (%s)", r.Framework, r.ID, r.Title))
				}
				fmt.Fprintf(w, "- **References:** %s\n", strings.Join(refs, " - "))
			}
			if len(f.Evidence) > 0 {
				// Markdown is a document rather than a screen, so the full
				// list is kept: a reader can scroll, and an auditor wants it.
				fmt.Fprintf(w, "- **Evidence:**\n")
				for _, e := range f.Evidence {
					fmt.Fprintf(w, "  - `%s`\n", e)
				}
			}
			if f.Err != "" {
				fmt.Fprintf(w, "- **Check error:** %s\n", f.Err)
			}
			fmt.Fprintf(w, "\n")
		}
	}

	// Accepted findings, listed apart so a waiver is never mistaken for a fix.
	if rep.Counts["accepted"] > 0 {
		fmt.Fprintf(w, "## Accepted findings\n\n")
		fmt.Fprintf(w, "These are real problems, knowingly carried rather than fixed. ")
		fmt.Fprintf(w, "They are excluded from the score but not from your risk.\n\n")
		fmt.Fprintf(w, "| Severity | Finding | ID | Reason accepted |\n| --- | --- | --- | --- |\n")
		for _, f := range rep.Findings {
			if f.Accepted == "" {
				continue
			}
			fmt.Fprintf(w, "| %s | %s | `%s` | %s |\n",
				f.Severity.String(), f.Title, f.ID, f.Accepted)
		}
		fmt.Fprintf(w, "\n")
	}

	// Passed controls, collapsed.
	fmt.Fprintf(w, "<details>\n<summary>Passed controls (%d)</summary>\n\n", rep.Counts["passed"])
	for _, f := range rep.Findings {
		if f.Passed {
			fmt.Fprintf(w, "- `%s` %s\n", f.ID, f.Title)
		}
	}
	fmt.Fprintf(w, "\n</details>\n")
}
